### ISSUE TITLE
error without optional telemetry dependency installed

### ISSUE THREAD

**Issue by gregors** [mana-ethereum/ethereumex#70]
Looks like telemetry was added recently as an optional dependency - but it doesn't look optional

```elixir Interactive Elixir (1.10.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Ethereumex.HttpClient.web3_client_version
** (UndefinedFunctionError) function :telemetry.execute/3 is undefined (module :telemetry is not available)
    :telemetry.execute([:ethereumex], %{counter: 1}, %{method_name: "web3_clientVersion"})
    (ethereumex 0.6.1) lib/ethereumex/counter.ex:59: Ethereumex.Counter.inc/2
    (ethereumex 0.6.1) lib/ethereumex/client/base_client.ex:505: Ethereumex.HttpClient.prepare_request/1
    (ethereumex 0.6.1) lib/ethereumex/client/base_client.ex:485: Ethereumex.HttpClient.server_request/2```

**Comment by InoMurko** [comment]
https://github.com/mana-ethereum/ethereumex/pull/73

**Comment by ayrat555** [comment]
resolved by https://github.com/mana-ethereum/ethereumex/pull/73
